# Generated by Django 3.1.1 on 2020-10-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_auto_20201024_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
