# Generated by Django 3.1.1 on 2020-10-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='District',
        ),
        migrations.RemoveField(
            model_name='user',
            name='State',
        ),
        migrations.AddField(
            model_name='post',
            name='District',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='State',
            field=models.TextField(blank=True, null=True),
        ),
    ]
