# Generated by Django 3.1.1 on 2020-10-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0005_auto_20201025_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
    ]
