# Generated by Django 3.1.1 on 2020-10-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0006_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='HasGarder',
            new_name='HasGarden',
        ),
    ]
